# Railway configuration for Nx monorepo deployment
# Single service that serves the API

[build]
command = "pnpm build:api"

[deploy]
# Start the Express server
startCommand = "node dist/apps/api/main.js"

[variables]
# Set the port for Railway
PORT = 4000
NODE_ENV = "production"
