# Railway configuration for Nx monorepo deployment
# Deploys apps/web (static site) and apps/api (Node.js server) separately

# API Service Configuration
[api]
source = "."
build = { command = "pnpm install && pnpm build:api" }
start = { command = "node dist/apps/api/main.js" }

[api.variables]
NODE_ENV = "production"
PORT = 3001

# Web Service Configuration  
[web]
source = "."
build = { command = "pnpm install && pnpm build:web" }
staticPublishPath = "dist/apps/web"

[web.variables]
NODE_ENV = "production"
