// DI Container tokens following Clean Architecture layers
export const TOKENS = {
  // Infrastructure Layer - HTTP and API Services
  HttpClient: 'IHttpClient',
  TodoApiService: 'ITodoApiService',
  AuthApiService: 'IAuthApiService',
  PatientApiService: 'IPatientApiService',
  UserApiService: 'IUserApiService',
  DoctorApiService: 'IDoctorApiService',
  AddressApiService: 'IAddressApiService',
  
  // Infrastructure Layer - Repositories
  TodoRepository: 'ITodoRepository',
  UserRepository: 'IUserRepository',
  PatientRepository: 'IPatientRepository',
  DoctorRepository: 'IDoctorRepository',
  AddressRepository: 'IAddressRepository',
  ScheduleRepository: 'IScheduleRepository',
  AppointmentRepository: 'IAppointmentRepository',

  // Infrastructure Layer - Services
  PasswordHashingService: 'IPasswordHashingService',
  JwtService: 'IJwtService',

  // Application Layer - CQRS Services (Interface-based for cleaner injection)
  TodoCommandService: 'ITodoCommandService',
  TodoQueryService: 'ITodoQueryService',
  AuthCommandService: 'IAuthCommandService',
  AuthQueryService: 'IAuthQueryService',
  PatientCommandService: 'IPatientCommandService',
  PatientQueryService: 'IPatientQueryService',
  UserQueryService: 'IUserQueryService',

  // Application Layer - Use Cases (Commands)
  CreateTodoUseCase: 'CreateTodoUseCase',
  UpdateTodoUseCase: 'UpdateTodoUseCase',
  DeleteTodoUseCase: 'DeleteTodoUseCase',
  ToggleTodoUseCase: 'ToggleTodoUseCase',
  RegisterUserUseCase: 'RegisterUserUseCase',
  LoginUserUseCase: 'LoginUserUseCase',
  ChangeUserPasswordUseCase: 'ChangeUserPasswordUseCase',
  CreatePatientUseCase: 'CreatePatientUseCase',
  CreateDoctorProfileCommandHandler: 'CreateDoctorProfileCommandHandler',
  CreateScheduleUseCase: 'CreateScheduleUseCase',
  UpdateScheduleUseCase: 'UpdateScheduleUseCase',
  DeleteScheduleUseCase: 'DeleteScheduleUseCase',
  CreateAppointmentUseCase: 'CreateAppointmentUseCase',
  UpdateAppointmentUseCase: 'UpdateAppointmentUseCase',
  DeleteAppointmentUseCase: 'DeleteAppointmentUseCase',
  ConfirmAppointmentUseCase: 'ConfirmAppointmentUseCase',
  CancelAppointmentUseCase: 'CancelAppointmentUseCase',
  RescheduleAppointmentUseCase: 'RescheduleAppointmentUseCase',

  // Application Layer - Use Cases (Queries)
  GetAllTodosQueryHandler: 'GetAllTodosQueryHandler',
  GetFilteredTodosQueryHandler: 'GetFilteredTodosQueryHandler',
  GetActiveTodosQueryHandler: 'GetActiveTodosQueryHandler',
  GetCompletedTodosQueryHandler: 'GetCompletedTodosQueryHandler',
  GetTodoStatsQueryHandler: 'GetTodoStatsQueryHandler',
  GetTodoByIdQueryHandler: 'GetTodoByIdQueryHandler',
  GetAllUsersQueryHandler: 'GetAllUsersQueryHandler',
  GetAllPatientsQueryHandler: 'GetAllPatientsQueryHandler',
  GetPatientByIdQueryHandler: 'GetPatientByIdQueryHandler',
  GetPatientStatsQueryHandler: 'GetPatientStatsQueryHandler',
  GetAllDoctorsQueryHandler: 'GetAllDoctorsQueryHandler',
  GetDoctorByIdQueryHandler: 'GetDoctorByIdQueryHandler',
  GetDoctorByUserIdQueryHandler: 'GetDoctorByUserIdQueryHandler',
  GetDoctorsBySpecializationQueryHandler: 'GetDoctorsBySpecializationQueryHandler',
  CheckDoctorProfileExistsQueryHandler: 'CheckDoctorProfileExistsQueryHandler',
  GetAllProvincesQueryHandler: 'GetAllProvincesQueryHandler',
  GetCitiesByProvinceCodeQueryHandler: 'GetCitiesByProvinceCodeQueryHandler',
  GetBarangaysByCityCodeQueryHandler: 'GetBarangaysByCityCodeQueryHandler',
  GetAllSchedulesQueryHandler: 'GetAllSchedulesQueryHandler',
  GetScheduleByIdQueryHandler: 'GetScheduleByIdQueryHandler',
  GetSchedulesByDateQueryHandler: 'GetSchedulesByDateQueryHandler',
  GetSchedulesByDoctorQueryHandler: 'GetSchedulesByDoctorQueryHandler',
  GetTodaySchedulesQueryHandler: 'GetTodaySchedulesQueryHandler',
  GetTodayDoctorQueryHandler: 'GetTodayDoctorQueryHandler',
  GetScheduleStatsQueryHandler: 'GetScheduleStatsQueryHandler',
  GetAllAppointmentsQueryHandler: 'GetAllAppointmentsQueryHandler',
  GetAppointmentByIdQueryHandler: 'GetAppointmentByIdQueryHandler',
  GetAppointmentsByPatientIdQueryHandler: 'GetAppointmentsByPatientIdQueryHandler',
  GetTodayAppointmentsQueryHandler: 'GetTodayAppointmentsQueryHandler',
  GetTodayConfirmedAppointmentsQueryHandler: 'GetTodayConfirmedAppointmentsQueryHandler',
  GetConfirmedAppointmentsQueryHandler: 'GetConfirmedAppointmentsQueryHandler',
  GetAppointmentsByDateQueryHandler: 'GetAppointmentsByDateQueryHandler',
  GetAppointmentsByDateRangeQueryHandler: 'GetAppointmentsByDateRangeQueryHandler',
  GetWeeklyAppointmentSummaryQueryHandler: 'GetWeeklyAppointmentSummaryQueryHandler',
  GetAppointmentStatsQueryHandler: 'GetAppointmentStatsQueryHandler',

  // Domain Layer - Services
  TodoDomainService: 'TodoDomainService',
  UserDomainService: 'UserDomainService',
  PatientNumberService: 'PatientNumberService',
  PhoneNumberService: 'PhoneNumberService',
  AgeCalculationService: 'AgeCalculationService',
  AppointmentDomainService: 'AppointmentDomainService',

  // Application Layer - Validation Services
  CreateTodoValidationService: 'CreateTodoValidationService',
  UpdateTodoValidationService: 'UpdateTodoValidationService', 
  DeleteTodoValidationService: 'DeleteTodoValidationService',
  ToggleTodoValidationService: 'ToggleTodoValidationService',
  TodoValidationService: 'TodoValidationService',
  RegisterUserValidationService: 'RegisterUserValidationService',
  LoginUserValidationService: 'LoginUserValidationService',
  UserValidationService: 'UserValidationService',
  CreatePatientValidationService: 'CreatePatientValidationService',
  GetPatientByIdValidationService: 'GetPatientByIdValidationService',
  PatientValidationService: 'PatientValidationService',
  GetDoctorByIdValidationService: 'GetDoctorByIdValidationService',
  GetDoctorsBySpecializationValidationService: 'GetDoctorsBySpecializationValidationService',
  DoctorValidationService: 'DoctorValidationService',
  GetCitiesValidationService: 'GetCitiesValidationService',
  GetBarangaysValidationService: 'GetBarangaysValidationService',
  AddressValidationService: 'AddressValidationService',
  CreateScheduleValidationService: 'CreateScheduleValidationService',
  UpdateScheduleValidationService: 'UpdateScheduleValidationService',
  DeleteScheduleValidationService: 'DeleteScheduleValidationService',
  GetScheduleByIdValidationService: 'GetScheduleByIdValidationService',
  GetSchedulesByDateValidationService: 'GetSchedulesByDateValidationService',
  GetSchedulesByDoctorValidationService: 'GetSchedulesByDoctorValidationService',
  ScheduleValidationService: 'ScheduleValidationService',
  CreateAppointmentValidationService: 'CreateAppointmentValidationService',
  UpdateAppointmentValidationService: 'UpdateAppointmentValidationService',
  DeleteAppointmentValidationService: 'DeleteAppointmentValidationService',
  ConfirmAppointmentValidationService: 'ConfirmAppointmentValidationService',
  CancelAppointmentValidationService: 'CancelAppointmentValidationService',
  RescheduleAppointmentValidationService: 'RescheduleAppointmentValidationService',
  GetAppointmentByIdValidationService: 'GetAppointmentByIdValidationService',
  GetAppointmentsByPatientIdValidationService: 'GetAppointmentsByPatientIdValidationService',
  GetAppointmentsByDateValidationService: 'GetAppointmentsByDateValidationService',
  GetAppointmentsByDateRangeValidationService: 'GetAppointmentsByDateRangeValidationService',
  AppointmentValidationService: 'AppointmentValidationService',
} as const;

// Type-safe token keys
export type TokenKey = keyof typeof TOKENS;
